//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtContest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureRate
    {
        public int PictureId { get; set; }
        public int JudgeId { get; set; }
        public double Rate { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual User User { get; set; }
    }
}
